### ISSUE TITLE
Comment and suggestion.

### ISSUE THREAD

**Issue by kingofthebongo2008** [sawickiap/MinScriptLang#1]
One particular problem that one faces very often in the gpu programming is the serialization and types for constant buffers and structures across c++ and hlsl, which takes enourmous amount of time and mostly looks the same code.
Floats, Float4, Float2, uint32_ts gather from the cpu, computed the offsets, etc. Textures is the same.

Ideally I would like to have a language that i describe the parameters and it generates c++ and hlsl code for reading and writing, so i can benefit of static type system.

It is not connected particularly to the parser, but just in case. Since you did quite good job on the allocators.

**Comment by sawickiap** [comment]
Thank you for the suggestion. I also think that such tool would be very useful.

However, this is out of scope of this project. MinScriptLang is a dynamically typed scripting language and has nothing to do with GPUs or shaders.
